Feature/saving 아껴쓰기 기능 개발
a-na-ba-da/frontend pull request #3
Opened 2023-06-29 02:27 UTC by hnsoo

### 추가된 기능 ### 
* 백엔드의 수정된 API 규격에 따라 아껴쓰기의 같이사요, 같이알아요의 데이터 파싱 과정 변경
* 서버에서 데이터를 가져오지 못했을 경우를 대비한 옵셔널 처리

2023-07-01 06:34 UTC, devjaeyoon requested changes
수고했고 console.log만 지우자!

2023-07-01 06:34 UTC, devjaeyoon commented on src/pages/Saving/BuyingPost.tsx
> +      console.log(res.data.detail);
console.log는 development branch에 올릴 때 필요한 코드가 아니니까 제거하자!

2023-07-01 06:38 UTC, hnsoo commented on src/pages/Saving/BuyingPost.tsx
> +      console.log(res.data.detail);
적용완료!

2023-07-01 06:41 UTC, merged

2023-07-01 11:06 UTC, PENEKhun commented on src/pages/Saving/BuyingPost.tsx
> +      console.log(res.data.detail);
@hnsoo @devjaeyoon 

production이 아닌이상 console.log가 지속적으로 필요할거 같은데

```javascript
// const isProduction = ENV에서 test인지 아닌지 불러온다
console.log = function() {
    if(isProduction) return;
    console.log.apply(this, arguments);
};
```

이런식으로 오버라이드하면
프로덕션코드에서 console.log를 안빼도 되지 않나요?

2023-07-01 11:12 UTC, PENEKhun commented on src/pages/Saving/BuyingPost.tsx
> +      console.log(res.data.detail);
내용 추가)

[링크](https://gitabout.com/3)

아예 이런 방법도 있네요.

2023-07-03 00:17 UTC, hnsoo commented on src/pages/Saving/BuyingPost.tsx
> +      console.log(res.data.detail);
링크 내용 좋네요 재윤이랑 어떻게할지 함 얘기해볼게요

2023-07-03 00:51 UTC, devjaeyoon commented on src/pages/Saving/BuyingPost.tsx
> +      console.log(res.data.detail);
좋은 아이디어인 것 같습니다! 바로 적용해보도록 하겠습니다 :)